spring.application.name=invoice-system
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# queries SQL en la consola
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=alpha
# Configuración de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
