spring.application.name=invoice-system
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# queries SQL en la consola
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=alpha
# Configuración de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://invoice_jjgy_user:Ky9SGeLINXsFZWxC3ceskDhk42bDXApH@dpg-d82ug4e7r5hc73cou9u0-a/invoice_jjgy
spring.datasource.username=invoice_jjgy_user
spring.datasource.password=Ky9SGeLINXsFZWxC3ceskDhk42bDXApH
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
